services:
  homepage-o-matic-frontend:
    image: phillipshreves/homepage-o-matic-frontend:latest
    pull_policy: missing
    build:
      context: ./frontend
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    container_name: homepage-o-matic-frontend
    environment:
      - BACKEND_URL=http://homepage-o-matic-backend:8080
    ports:
      - 40081:3000
    depends_on:
      homepage-o-matic-backend:
        condition: service_started
    restart: always

  homepage-o-matic-backend:
    image: phillipshreves/homepage-o-matic-backend:latest
    pull_policy: missing
    container_name: homepage-o-matic-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    environment:
      - NODE_ENV=production
    working_dir: /app/src
    restart: always
